
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: basic-auth
      nginx.ingress.kubernetes.io/auth-realm: "Authentication Required prometheus"
      cert-manager.io/cluster-issuer: self-signed-issuer
    hosts:
      - <domain>
    tls:
      - secretName: self-signed-cert
        hosts:
          - <domain>
  persistentVolume:
    enabled: true
    storageClass: nfs-client
    size: 32Gi

alertmanager:
  persistence:
    storageClass: nfs-client
