
- name: Installing vim
  become: yes
  apt:
    name: vim
    state: present

- name: Installing wget
  become: yes
  apt:
    name: wget
    state: present

- name: Installing curl
  become: yes
  apt:
    name: curl
    state: present

- name: Add aliases and PS1 for all users
  become: yes
  blockinfile:
    path: /home/{{ item }}/.bashrc
    block: |
      alias ..="cd .."
      alias cat="ccat"
      alias df="df -h"
      alias sudo="sudo "
      alias l="ls --color -lhF"
      alias ll="ls --color=auto -lha"

      BRACKET_COLOUR=$(tput setaf 247)
      USERNAME_COLOUR=$(tput setaf 4)
      AT_COLOUR=$(tput setaf 2)
      HOSTNAME_COLOUR=$(tput setaf 3)
      PATH_COLOUR=$(tput setaf 6)
      RESET=$(tput sgr0)
      PS1='\[${USERNAME_COLOUR}\]\u\[${AT_COLOUR}\]@\[${HOSTNAME_COLOUR}\]\h \[${PATH_COLOUR}\]\w\[${BRACKET_COLOUR}\] \$\[${RESET}\] '
  loop: "{{ users }}"

- name: Create .bash_profile for root
  become: yes
  file:
    path: /root/.bash_profile
    state: touch

- name: Add aliases and PS1 for root
  become: yes
  blockinfile:
    path: /root/.bash_profile
    block: |
      alias ..="cd .."
      alias cat="ccat"
      alias l="ls --color -lhF"
      alias ll="ls --color=auto -lha"

      BRACKET_COLOUR=$(tput setaf 247)
      USERNAME_COLOUR=$(tput setaf 1)
      AT_COLOUR=$(tput setaf 2)
      HOSTNAME_COLOUR=$(tput setaf 3)
      PATH_COLOUR=$(tput setaf 6)
      RESET=$(tput sgr0)
      PS1='\[${USERNAME_COLOUR}\]\u\[${AT_COLOUR}\]@\[${HOSTNAME_COLOUR}\]\h \[${PATH_COLOUR}\]\w\[${BRACKET_COLOUR}\] \$\[${RESET}\] '

- name: Check if ccat is already installed
  become: yes
  stat:
    path: /usr/local/bin/ccat
  register: ccat_stat

- name: Installing ccat
  become: yes
  shell: |
    cd /opt
    wget https://github.com/jingweno/ccat/releases/download/v1.1.0/linux-amd64-1.1.0.tar.gz
    tar xfz linux-amd64-1.1.0.tar.gz
    cp linux-amd64-1.1.0/ccat /usr/local/bin/
    chmod +x /usr/local/bin/ccat
    rm linux-amd64-1.1.0.tar.gz
    rm -r linux-amd64-1.1.0
  when: not ccat_stat.stat.exists
