{{- if .Values.persistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "radio-app.fullname" . }}
  labels:
{{- include "radio-app.labels" . | nindent 4 }}
spec:
  accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 4 }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}"
{{- end -}}
