apiVersion: v1
kind: Service
metadata:
  name: icecast-service
  labels:
{{- include "radio-app.labels" . | nindent 4 }}
spec:
  selector:
    app: icecast
    {{- include "radio-app.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
