---

- name: Install helm diff
  tags: ["kube", "base"]
  kubernetes.core.helm_plugin:
    plugin_path: "https://github.com/databus23/helm-diff"
    state: present

- name: Add helm repo jetstack
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Add helm repo ingress-nginx
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Add helm repo kubernetes-dashboard
  kubernetes.core.helm_repository:
    name: kubernetes-dashboard
    repo_url: "https://kubernetes.github.io/dashboard"

- name: Add helm repo twuni
  kubernetes.core.helm_repository:
    name: twuni
    repo_url: "https://helm.twun.io"

- name: Add helm repo nfs-subdir-external-provisioner
  kubernetes.core.helm_repository:
    name: nfs-subdir-external-provisioner
    repo_url: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner"

- name: Add drone helm repo drone
  kubernetes.core.helm_repository:
    name: drone
    repo_url: "https://charts.drone.io"

- name: Add helm repo linkerd
  kubernetes.core.helm_repository:
    name: linkerd-edge
    repo_url: "https://helm.linkerd.io/edge"

- name: Add prometheus helm repo prometheus-community
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"

- name: Add grafana helm repo grafana
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Add helm repo jupyterhub
  kubernetes.core.helm_repository:
    name: jupyterhub
    repo_url: "https://jupyterhub.github.io/helm-chart"

- name: Update helm repos
  command: "helm repo update"
