---

- name: Create namespace monitoring
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring

- name: Generate htpasswd string
  shell: htpasswd -Bbn admin "{{ admin_password }}" | base64
  register: htpasswd_base64

- name: Create basic-auth secret for prometheus ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: basic-auth
        namespace: monitoring
      type: Opaque
      data:
        auth: "{{ htpasswd_base64.stdout }}"

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    namespace: monitoring
    create_namespace: yes
    values: "{{ lookup('file', 'files/prometheus_values.yml') | from_yaml }}"

- name: Install grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    namespace: monitoring
    values: "{{ lookup('file', 'files/grafana_values.yml') | from_yaml }}"
    values_files:
      - "https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/values.yaml"

- name: Create postgres password secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-secret
        namespace: monitoring
      type: Opaque
      data:
        chirpse-db-password: "{{ chirpse_db_password | b64encode }}"

- name: Install postgres exporter
  kubernetes.core.helm:
    name: postgres-exporter
    namespace: monitoring
    chart_ref: prometheus-community/prometheus-postgres-exporter
    chart_version: 4.6.0
    values: "{{ lookup('file', 'files/postgres_exporter_values.yml') | from_yaml }}"
