version: 2
ethernets:
  ens18:
    addresses:
      - "${ip_address}"
    routes:
      - to: 0.0.0.0/0
        via: "${gateway}"
        on-link: true
    nameservers:
      addresses:
        - "${dns1}"
        - "${dns2}"
